import java.util.Random;
import java.util.Scanner;

public class GuessingGame {

    public GuessingGame() {
        // new Scanner variable named input, this will be what you use to store the user input
        Scanner input = new Scanner(System.in);

        boolean correctGuess = false;
        int guess = 0;
        int increment = 0;

        System.out.println("Hello user, What is your name?");

        // new String variable named name which is set equal to input.nextLine()
        String name = input.nextLine();

        System.out.println("Welcome " + name + " I'm thinking of a number between 1 and 100.");

        // new random object by calling the Random constructor
        Random rand = new Random();

        // int named number and set it equal to rand.nextInt(100)
        // rand.nextInt(100) chooses the next number generated by rand from the limit of 1 to 100
        int number = rand.nextInt(100);

        //Print "Try to guess my number."
        System.out.println("Try to guess my number.");

        // condition to correctGuess being equal to false
        while (correctGuess == false) {
            increment++;

            //try catch statement that catches Exception e
            try {
                // guess equal to input.nextInt()
                guess = input.nextInt();
            }
            catch (Exception e) {
                // new String called badInput and set it to input.next()
                String badInput = input.next(); //needed to progress past the bad input
                System.out.println("That's not an integer, try again");

                // continue to skip back to the beginning of the while loop
                continue;
            }

            // if statement to see if the guess is greater than 100 or less than 1
            if (guess > 100 || guess < 1) {
                System.out.println("You're guess is out of range. Please try again.");
            }
            // else-if statement to check if the guess is greater than the number
            else if (guess > number) {
                System.out.println("You're guess is too high. Please try again.");
            }
            // else-if statement to check if the guess is less than the number
            else if (guess < number) {
                System.out.println("You're guess is too low. Please try again.");
            }
            // else-if statement to check if the guess is equal to number
            else if (guess == number) {
                System.out.println("Well done, " + name + "! You found my number in " + increment + " tries!");

                correctGuess = true;
            }
        }
    }
}
